id: P393C8F06
initial_creation_type: input
source_metadata:
  Title: Ratnagotravibhāgo mahāyānottaratantraśāstram
  Editor: Johnston, E.H.
  Publisher: Srisatguru Publications
  Place of Publication: Delhi
  Year: '1991'
  Prathamaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvitīyaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Tṛtīyaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturthaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Paṃcamaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:56:26.984857'
last_modified_at: '2022-03-08T16:56:26.984869'
